name: commute-tmle
channels:
  - nodefaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.15.2=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - astor=0.8.1=pyhd8ed1ab_1
  - autograd=1.7.0=pyhd8ed1ab_1
  - autograd-gamma=0.5.0=pyhd8ed1ab_1
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - cached_property=1.5.2=pyha770c72_1
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.9.0=pyh707e725_1
  - contourpy=1.3.1=py313h33d0bda_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - fonttools=4.57.0=py313h8060acc_0
  - formulaic=1.1.1=pyhd8ed1ab_0
  - freetype=2.13.3=h48d6fc4_0
  - graphlib-backport=1.0.3=pyhd8ed1ab_0
  - greenlet=3.1.1=py313h46c70d0_1
  - hazardous=0.1.0=pyhecae5ae_0
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - hydra-submitit-launcher=1.2.0=pyhd8ed1ab_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - interface_meta=1.3.0=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - kiwisolver=1.4.7=py313h33d0bda_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libdeflate=1.23=h4ddbbb0_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - libmpdec=4.0.0=h4bc722e_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lifelines=0.30.0=pyhd8ed1ab_1
  - mako=1.3.9=pyhd8ed1ab_0
  - markupsafe=3.0.2=py313h8060acc_1
  - matplotlib-base=3.10.1=py313h129903b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.4=py313h17eae1a_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_0
  - optuna=4.2.1=pyhd8ed1ab_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py313ha87cce1_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.1.0=py313h8db990d_0
  - pip=25.0.1=pyh145f28c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - python=3.13.2=hf636f53_101_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=6_cp313
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py313h8060acc_2
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - scikit-learn=1.6.1=py313h8ef605b_0
  - scipy=1.15.2=py313h86fcf2b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=78.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlalchemy=2.0.40=py313h536fd9c_0
  - statsmodels=0.14.4=py313ha014f3b_0
  - submitit=1.5.2=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.13.1=hf5ce1d7_0
  - typing_extensions=4.13.1=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - wrapt=1.17.2=py313h536fd9c_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - black==25.1.0
      - brotli==1.1.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - ecos==2.0.14
      - feather-format==0.4.1
      - h5py==3.13.0
      - idna==3.10
      - inflate64==1.0.1
      - llvmlite==0.44.0
      - multivolumefile==0.2.3
      - mypy-extensions==1.0.0
      - numba==0.61.2
      - numexpr==2.10.2
      - osqp==0.6.7.post3
      - pathspec==0.12.1
      - platformdirs==4.3.7
      - psutil==7.0.0
      - py7zr==0.22.0
      - pyarrow==19.0.1
      - pybcj==1.0.3
      - pycox==0.3.0
      - pycryptodomex==3.22.0
      - pyppmd==1.1.1
      - pytmle==0.1.0
      - pyzstd==0.16.2
      - qdldl==0.1.7.post5
      - requests==2.32.3
      - scikit-survival==0.24.1
      - texttable==1.7.0
      - torchtuples==0.2.2
      - urllib3==2.4.0
