seed: 1234
min_age_at_index: 70
input_csv: ./data/a_inputs/mock_input.csv
dates_set_path: ./data/b_dates_set
covariates_merged_path: ./data/c_covariates_merged
output_path: ${hydra:sweep.dir}/${hydra:sweep.subdir}

mock_data:
  n: 1000