defaults:
- _self_
- /hydra/callbacks:
   - log_job_return_callback
- survivalboost_params:
   - default

general:
  seed: 1234
  min_age_at_index: 70.0
  input_csv: ./data/a_inputs/mock_input.csv
  dates_set_path: ./data/b_dates_set
  covariates_merged_path: ./data/c_covariates_merged
  output_path: ${hydra:sweep.dir}/${hydra:sweep.subdir}
  store_json: false
  pickle_tmle: false

fit:
  exclude_columns:
    - patient_id
    - index_date
    - covid_vaccine # has to be excluded because there will be no overlap for pre-pandemic controls
  n_jobs: 8
  n_trials: 100
  n_folds_outer: 5
  n_folds_inner: 3
  eval_metric: c_antolini_all
  max_updates: 500
  target_times:
    - 100
    - 200
    - 300
    - 400
    - 500
    - 600
    - 700
  perform_propensity_score_matching: true
  propensity_score_matching_caliper: 0.2
  propensity_score_matching_grid_search: true
  propensity_score_matching_calibrate: true # for propensity scores in PSM
  propensity_score_calibration_method: null # for propensity scores in PyTMLE
  control_pool_subsample_factor: null
  subset_condition: event_time > 30
  optuna_storage: null
  tune_hyperparameters: true
  explore_effect_heterogeneity: true
  hte_quantile: 0.05
  run_evalues_benchmark: false

mock_data:
  n: 1000